# Generated by Django 3.2.6 on 2023-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='tumor_image',
            field=models.ImageField(null=True, upload_to='tumor_images/'),
        ),
    ]
