# Generated by Django 3.2.6 on 2023-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploadedimage_tumor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='mask_image',
            field=models.ImageField(null=True, upload_to='mask_images/'),
        ),
    ]
