# Generated by Django 3.2.6 on 2023-07-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uploadedimage_mask_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='mask_image',
            new_name='masked_image',
        ),
    ]
