# Generated by Django 3.2.6 on 2023-07-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_uploadedimage_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='Area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='Stage',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
