# Generated by Django 3.2.6 on 2023-07-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230726_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='Stage2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
