# Generated by Django 3.2.16 on 2023-08-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230823_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='app',
            new_name='overall_report',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='report',
            new_name='video_report',
        ),
    ]
