# Generated by Django 3.2.16 on 2023-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230824_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='conclusion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
