# Generated by Django 3.2.16 on 2023-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_analysisresult_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_report', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
