# Generated by Django 3.2.16 on 2023-08-24 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_telegramanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramanalysis',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
