# Generated by Django 3.2.16 on 2023-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_telegramanalysis_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='overall_report',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='video_report',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='telegramanalysis',
            name='channel_report',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
