# Generated by Django 3.2.16 on 2023-09-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230916_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramanalysis',
            name='conclusion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
